### ISSUE TITLE
How to add normal feature references to the main feature?

### ISSUE THREAD

**Issue by PhilAndrew** [wav/osgi-tooling#1]
I want to add a feature reference to the applications feature.

    <?xml version="1.0" encoding="UTF-8"?><features xmlns="http://karaf.apache.org/xmlns/features/v1.2.0" name="universe_osgi_helloworld">
          <feature name="universe_osgi_helloworld" version="1.0">
            <feature>scr</feature>

To do this I need to change the source code of osgi-tooling

    lazy val feature = KarafPackagingKeys.featuresProjectFeature :=
      Some(
        FeaturesXml.Feature(name.value, Some(version.value),
            Set(FeatureRef("scr")) ++
            Set(KarafPackagingKeys.featuresScalaFeature.value.Ref,
            KarafPackagingKeys.featuresProjectBundle.value)))

The changed line             Set(FeatureRef("scr")) ++

So I think I need to change the source code to add a new key for feature references.

**Comment by PhilAndrew** [comment]
I add some very messy hacky code to make it work in my fork https://github.com/PhilAndrew/osgi-tooling/commit/c623ece77e6f8482a2651a08b0f6c92e640d2b53

**Comment by wav** [comment]
Hi Phil, 

A features.xml (the top level features element) is a collection of repositories (not added yet) and features (`Feature`). This collection represented by the setting  `featuresElements`.

A feature (`Feature`) is a collection of dependencies. Dependencies are defined using the `Bundle` and `FeatureRef` elements.

What you would like to do is append the project/application feature in your `build.sbt` like so:

```scala
featuresProjectFeature <<= featuresProjectFeature map { pf =>
  pf.copy(elems = pf.elems + FeatureRef("scr"))
}
```

**Comment by wav** [comment]
Have a look at wav/osgi-tooling@20b5da1821f44acdb5b96f8efee1ab07c08ec3a8

**Comment by PhilAndrew** [comment]
Thanks a lot! I'm using this to deploy to Karaf, we may be doing a multi-month project using this, Scala, OSGi, Karaf, so this is very useful. Can I ask, the MBean part uses password authentication, are there any other authentication mechanisms available? I think there is a key system with Karaf but have not looked into it in detail.

**Comment by wav** [comment]
`sbt-karaf` uses JMX over RMI to manage the Karaf instance it connects to. With RMI, as I understand it, you cannot use keys/certificates. What you can do though is access the instance through an SSH tunnel.

For the development, password authentication should be ok as long if you're accessing the Karaf instance over a secure connection (an ssh tunnel).

**Comment by PhilAndrew** [comment]
New question, if I wish to add bundles to my Karaf file, then am I supposed to do it like this (not yet tested but you get the idea).

KarafPackagingKeys.featuresProjectFeature := {
  val pf: FeaturesXml.Feature = KarafPackagingKeys.featuresProjectFeature.value
  pf.copy(elems = pf.elems ++ Set(
    FeatureRef("scr"),
    FeaturesXml.Bundle("mvn:pl.newicom/schale_2.11/1.0.1"),
    FeaturesXml.Bundle("mvn:com.typesafe.scala-logging/scala-logging_2.11/3.1.0"),
    FeaturesXml.Bundle("mvn:ch.qos.logback/logback-classic/1.1.3"),
    FeaturesXml.Bundle("mvn:com.typesafe.akka/akka-actor_2.11/2.4-M1")
  ))
}

libraryDependencies += "pl.newicom" % "schale_2.11" % "1.0.1"

libraryDependencies += "com.typesafe.scala-logging" %% "scala-logging" % "3.1.0"

libraryDependencies += "ch.qos.logback" % "logback-classic" % "1.1.3"

libraryDependencies += "com.typesafe.akka" %% "akka-actor" % "2.4-M1"

**Comment by wav** [comment]
Yes. Declare your bundles separately to your sbt dependencies.

I was thinking of validating bundles against artifacts. But I never got
that far.

**Comment by wav** [comment]
FeaturesXml was originally created because it was the simplest way to generate or append an existing feature file and start automating things with sbt. But I didn't take it far as I was experimenting/learning.

Ideally I'd like to do what the `karaf-maven-plugin` which I looks like:
1. Find all artifacts that are bundles (a manifest that has a `BundleSymbolic-Name`) or features and build 2 FeaturesXml and add them as dependencies to the project feature.
3. If an artifact is not a bundle, make a wrapped bundle by constructing a url like `wrap:mvn:....$BundleSymbolic-Name`.

These are my thoughts:
1. Should be easy. Select all the artifacts from the sbt.UpdateReport.
2. I would add `FeaturesXml.WrappedBundle`, in your build.sbt the you would specify manifest headers manually. A default `BundleSymbolic-Name` and version header would be inferred from the artifact name and group.
3. I would not do, unless I can find a way of running the `karaf:features-validate-descriptor` goal.

Should this be done, I think we can happily generate a kar file.

What do you think? Suggestions?

**Comment by PhilAndrew** [comment]
Yes FeaturesXml is a good way to get started.

So one problem I have now is given that I have some dependencies.

libraryDependencies += "pl.newicom" % "schale_2.11" % "1.0.1"
libraryDependencies += "com.typesafe.scala-logging" %% "scala-logging" % "3.1.0"
libraryDependencies += "ch.qos.logback" % "logback-classic" % "1.1.3"
libraryDependencies += "com.typesafe.akka" %% "akka-actor" % "2.4-M2"

I need to make the feature have the dependencies of the dependencies of the dependencies ... etc. for the feature to install and start, otherwise Karaf will complain it can't install the bundle.

    FeaturesXml.Bundle("mvn:com.typesafe.akka/akka-actor_2.11/2.4-M2"),
    FeaturesXml.Bundle("wrap:mvn:ch.qos.logback/logback-classic/1.1.3"),
    FeaturesXml.Bundle("wrap:mvn:ch.qos.logback/logback-core/1.1.3"),
    FeaturesXml.Bundle("wrap:mvn:com.typesafe/config/1.3.0"),
    FeaturesXml.Bundle("wrap:mvn:pl.newicom/schale_2.11/1.0.1"),
    FeaturesXml.Bundle("wrap:mvn:com.typesafe.scala-logging/scala-logging_2.11/3.1.0")

Is that due to my lack of understanding? Is that what you think your first part would do (1,2,3)?

Building a kar is not a *need* for me at the moment but its a good idea. Can you also send me an email and say hi please?

**Comment by wav** [comment]
Documentation has been updated. Closed with a36a2acece2a62dbf187769a1a33b1e6c4d8f5e2.

Appending `featuresXml` or `featuresProjectFeature` is required in the following situations:

- Using a non `mvn:` url
`FeaturesXml.Bundle("http://...")`

- Use wrapping instructions
`FeaturesXml.WrappedBundle(url, manifest)`

**Comment by PhilAndrew** [comment]
This is interesting, I'll likely try this today

**Comment by PhilAndrew** [comment]
I took a look at it now, seems your pulling transitive dependencies now. That's nice.

**Comment by PhilAndrew** [comment]
What is the current way to add

<feature>camel-blueprint</feature>

I tried featuresRequired := Map("camel-blueprint" -> "*") but it fails with a compile error.

**Comment by wav** [comment]
The up-to-date key and syntax reference is documented as example projects. If this is failing to compile, it's probably a missing import (hint: `*Plugin.autoImport._`, `*Keys._`). 

See: https://github.com/wav/osgi-tooling/blob/master/KarafPackagingPlugin.md and the examples that are linked. The examples are integration tests so use these as reference when the build is passing.

Also make sure you're using sbt `0.13.9`.
