### ISSUE TITLE
Building on windows

### ISSUE THREAD

**Issue by PhilAndrew** [wav/osgi-tooling#5]
In order to build on Windows I must do two things.
1. Find the props.scala files and where it has ../../../../ etc in the props.scala file copy the contents from the other real Scala props.scala file to this file for all props.scala.
2. Ivy.scala, around line 37, change to:

    val CLASSIFIER_ATTRIBUTE = "e:classifier"
    val extra = url.classifer match {
      case Some(classifier) => Map(
        "classifier" -> classifier,
        // Satisfy: MavenRepositoryResolver.getClassifier
        CLASSIFIER_ATTRIBUTE -> classifier
      )
      case _ => Map.empty
    }

Delete the unused import statement after doing this.

**Comment by wav** [comment]
For 1. I'll see what i can do about removing `props.scala`

For 2. The `sbt-maven-resolver` dependency is missing.

I'll clean up the build to address these.

**Comment by wav** [comment]
Windows 10 is happy with b5f563a5eeec42ac2d8a5aeeaa2567569ec9f2d5.

Scripted tests still need to be updated to do the same.

**Comment by wav** [comment]
Everything should just work now with 3db862f1c445f21242aaf4e66baec8788d1451af if you're using the packaging functionality.

With regards to managing karaf, the task `karafResetServer` in `sbt-karaf` has some permissions error. If this affects you and you want to solve it, you're welcome to submit a PR.

The Pax settings are not adequately tested, which raises this issue #7. If you have any input, that'd be great.

**Comment by PhilAndrew** [comment]
Do you have a full time job as a Scala programmer?

**Comment by wav** [comment]
Nah. Full time C#. I use scala any  chance I get.

If you have any Qs not directly related to issues, you can PM me on
`eywassim at gmail`.
