### ISSUE TITLE
How to generate wrapped feature dependency?

### ISSUE THREAD

**Issue by PhilAndrew** [wav/osgi-tooling#8]
Some features need to be wrapped.

For example:

    "org.json" % "json" % "20140107",

generates

    <bundle start="false" dependency="true">mvn:org.json/json/20140107</bundle>

However it should start with wrap:

How to wrap?

Creating bundles for non OSGi third party dependencies
https://karaf.apache.org/manual/latest/developers-guide/creating-bundles.html

**Comment by wav** [comment]
If the dependency appears in your project feature, you can transform the project's feature in `featuresProjectFeature`. I've add an example test to illustrate the transform here 00f5a6cb8df7cfd1f83863a10397d4d076f3a0c1.

I'll have to have more of a think before adding it. 

I'm planning to implement the defaults described by pax url first which should address the case you've described.
> https://ops4j1.jira.com/wiki/display/paxurl/Wrap+Protocol#WrapProtocol-defaultinstructions

**Comment by wav** [comment]
Defaults are addressed in 3d60605e7fbb813b990abf36152bb484b63e6f0d
